name: dev

services:
  backend:
    container_name: backend
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
      target: development
    restart: unless-stopped
    env_file:
      - ../.env.dev
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
      - "2345:2345" # dlv debug
    command: air -c .air.toml
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "2"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://backend:8000/health"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 15s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dev-network

  frontend:
    container_name: frontend
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      target: development
    restart: unless-stopped
    volumes:
      - ../frontend:/app
      - /app/node_modules # don't allow local node_modules to be mounted into the container
    ports:
      - "5173:5173"
    command: sh -c "VITE_API_URL=http://localhost:8000 bun run dev -- --host"
    depends_on:
      - backend
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
