FROM oven/bun:alpine AS development

WORKDIR /app

COPY frontend/package.json frontend/bun.lock ./

RUN bun install --frozen-lockfile

COPY frontend/ .

ARG VITE_API_URL

RUN VITE_API_URL=${VITE_API_URL} bun --verbose run build

FROM caddy:2-alpine as production
COPY caddy/Caddyfile.frontend.prod /etc/caddy/Caddyfile
COPY --from=development /app/dist /srv